export const keys = [
    { id: "1", class: "reset", key: "AC" },
    { id: "2", class: "number", key: "π" },
    { id: "3", class: "factorial", key: "!" },
    { id: "4", class: "del", key: "Del" },
    { id: "5", class: "square-root", key: "√" },
    { id: "6", class: "exponentiation", key: "^" },
    { id: "7", class: "percentage", key: "%" },
    { id: "8", class: "basicOperation", key: "÷" },
    { id: "9", class: "number", key: "7" },
    { id: "10", class: "number", key: "8" },
    { id: "11", class: "number", key: "9" },
    { id: "12", class: "basicOperation", key: "x" },
    { id: "13", class: "number", key: "4" },
    { id: "14", class: "number", key: "5" },
    { id: "15", class: "number", key: "6" },
    { id: "16", class: "basicOperation", key: "-" },
    { id: "17", class: "number", key: "1" },
    { id: "18", class: "number", key: "2" },
    { id: "19", class: "number", key: "3" },
    { id: "21", class: "basicOperation", key: "+" },
    { id: "20", class: "changeTypeNumber", key: "+/-" },
    { id: "23", class: "number", key: "0" },
    { id: "22", class: "number", key: "." },
    { id: "24", class: "equal", key: "=" },
];
