export const keys = [
    { id: "1", class: "number", key: "7" },
    { id: "2", class: "number", key: "8" },
    { id: "3", class: "number", key: "9" },
    { id: "4", class: "del", key: "Del" },
    { id: "5", class: "number", key: "4" },
    { id: "6", class: "number", key: "5" },
    { id: "7", class: "number", key: "6" },
    { id: "8", class: "operation", key: "+" },
    { id: "9", class: "number", key: "1" },
    { id: "10", class: "number", key: "2" },
    { id: "11", class: "number", key: "3" },
    { id: "12", class: "operation", key: "-" },
    { id: "13", class: "number", key: "." },
    { id: "14", class: "number", key: "0" },
    { id: "15", class: "operation", key: "÷" },
    { id: "16", class: "operation", key: "x" },
    { id: "17", class: "reset", key: "Reset" },
    { id: "19", class: "equal", key: "=" },
];
