export const keys = [
    { class: "number", key: "7" },
    { class: "number", key: "8" },
    { class: "number", key: "9" },
    { class: "del", key: "Del" },
    { class: "number", key: "4" },
    { class: "number", key: "5" },
    { class: "number", key: "6" },
    { class: "operation", key: "+" },
    { class: "number", key: "1" },
    { class: "number", key: "2" },
    { class: "number", key: "3" },
    { class: "operation", key: "-" },
    { class: "number", key: "." },
    { class: "number", key: "0" },
    { class: "operation", key: "÷" },
    { class: "operation", key: "x" },
    { class: "reset", key: "Reset" },
    { class: "equal", key: "=" },
];
